#!/bin/bash

if test \! -c /dev/rtai_shm; then
	mknod -m 666 /dev/rtai_shm c 10 254
fi
for n in `seq 0 9`; do
	f=/dev/rtf$n
	if test \! -c $f; then
		mknod -m 666 $f c 150 $n
	fi
done

prefix=`rtai-config --prefix`
arch=`rtai-config --arch`
insmod=/sbin/insmod

if [ "$prefix" == "" ]; then 
echo "ERROR: please set your PATH variable to <rtai-install>/bin"
exit
fi

MODULES=$prefix/modules

#sync paranoia might be useful

sync
$insmod $MODULES/rtai_hal.ko IsolCpusMask=0;
sync
$insmod $MODULES/rtai_sched.ko;
sync
$insmod $MODULES/rtai_sem.ko;
sync
$insmod $MODULES/rtai_mbx.ko;
sync
$insmod $MODULES/rtai_msg.ko;
sync
$insmod $MODULES/rtai_shm.ko;
sync
