#!/bin/bash

MODULES=/usr/realtime/modules

#sync paranoia might be useful

insmod $MODULES/rtai_hal.ko IsolCpusMask=0;
sync
insmod $MODULES/rtai_sched.ko;
sync
insmod $MODULES/rtai_sem.ko;
sync
insmod $MODULES/rtai_mbx.ko;
sync
insmod $MODULES/rtai_shm.ko;
sync
